dist: trusty

language: go

go:
    - 1.9.x
    - "1.10"

before_script:
  - echo $HOSTNAME
  - mkdir -p $GOPATH/bin
  - wget --version
  - wget https://releases.hashicorp.com/consul/1.0.6/consul_1.0.6_linux_amd64.zip
  - wget https://releases.hashicorp.com/vault/0.9.3/vault_0.9.3_linux_amd64.zip
  - unzip -d $GOPATH/bin consul_1.0.6_linux_amd64.zip
  - unzip -d $GOPATH/bin vault_0.9.3_linux_amd64.zip
  - vault --version
  - consul --version
