dist: trusty

language: go

go:
    - 1.8.x
    - 1.9.x
    - tip

before_script:
  - echo $HOSTNAME
  - mkdir -p $GOPATH/bin
  - wget --version
  - wget https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
  - wget https://releases.hashicorp.com/vault/0.8.3/vault_0.8.3_linux_amd64.zip
  - unzip -d $GOPATH/bin consul_1.0.0_linux_amd64.zip
  - unzip -d $GOPATH/bin vault_0.8.3_linux_amd64.zip
  - vault --version
  - consul --version
